package main

const TMPL = `// Code generated by fielder. DO NOT EDIT.

package {{ .Package }}

const({{- range $i, $f := .Fields }}
	{{ $.Type }}_{{ $f.Name }} = "{{ $f.SQLFieldName -}}"
{{- end }}
)`
